#!/usr/bin/env bash
# Test harness for the front door's administration of the carried
# families: family discovery is a filesystem check, and a family's
# converge core is an idempotent installer — a bootstrap from nothing,
# a repair after deliberate drift in a suite-owned file, and a no-op on
# the resulting compliant estate, with hook wiring written only by the
# consented wire-hooks path and the retired merged verb removed.
#
# The consolidated act is exercised at the end over a project carrying
# one integrated family and one carried-but-unintegrated family: marker
# discovery splits them, the consented family is administered in the
# same pass while the declined one is left untouched, and the closing
# table's cells — carried version, project-stamped version, outcome —
# are read back off the filesystem the run leaves behind. The dialogue
# itself — the single bootstrap question, the recorded decline, the
# printed table — is prompt-realized and carries no deterministic
# check here; its verification is the implementation audit.
#
# Three things converge does that nothing else does are exercised here
# against the estate a real run leaves behind: it places the corpus view's
# built bundle at the project's pin and stamps it, it sweeps the payloads
# and story sections earlier suite versions owned, and it materializes the
# colliding audit verb family-prefixed per the integration contract.
#
# @story: one-command-suite-upkeep
# @story: converge-project-estate
# @decision: built-bundle-fetched-at-pin
# @decision: vendored-skills
set -uo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
suite_repo="$(cd "$here/../../.." && pwd)"
planner_core="$suite_repo/plugins/ok/families/ok-planner/admin/converge"
suite_version=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
  "$suite_repo/plugins/ok/.claude-plugin/plugin.json" | head -1)

fail=0
fails=0
ok()   { echo "ok: $1"; }
bad()  { echo "FAIL: $1"; fail=1; fails=$((fails + 1)); }

section() { :; }  # readability marker; sections carry no machinery

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
cd "$tmp"
git init -q .
git -c user.email=test@example.com -c user.name=test commit -q --allow-empty -m init

# --- Discovery is a filesystem check (the contract's markers) ---------------
section one-command-suite-upkeep
[ ! -d .ok-planner ] && ok "no marker, no integration: .ok-planner/ absent means bootstrap candidate" \
  || bad "fresh project unexpectedly carries .ok-planner/"

# A retired merged verb from an earlier suite version, awaiting removal.
mkdir -p .claude/skills/true-up
echo "stale merged verb" > .claude/skills/true-up/SKILL.md

# --- Pass 1: bootstrap from nothing -----------------------------------------
section converge-project-estate
out=$(bash "$planner_core" 2>&1)
if [ -d .ok-planner/issues ] && [ -d .ok-planner/history/sprints ]; then
  ok "bootstrap materializes the estate layout"
else
  bad "bootstrap did not create the estate layout"; echo "$out"
fi
grep -q "Materialized by ok-planner v${suite_version}" .ok-planner/CLAUDE.md \
  && ok "estate guide stamped with the suite version (front-door manifest)" \
  || bad "estate guide missing the suite-version stamp"
[ -f .claude/rules/ok-planner-cheatsheet.md ] \
  && ok "cheatsheet materialized" || bad "cheatsheet missing"
[ -x .ok-planner/hooks/session-start ] \
  && ok "session-start hook materialized into the estate" || bad "session-start hook missing"
n=$(find .claude/skills -name SKILL.md | wc -l | tr -d ' ')
[ "$n" -ge 10 ] && ok "vendored skill set written ($n files)" || bad "vendored skill set incomplete ($n files)"
[ ! -e .claude/skills/true-up ] \
  && ok "retired merged true-up verb removed on converge" \
  || bad "retired merged true-up verb still present"
grep -rq "ok-planner-audit-check" .claude/skills/ \
  && bad "renderer corrupted a support-script path (ok-planner-audit-check)" \
  || ok "renderer leaves support-script paths intact (bin/audit-check)"
grep -q "WIRING NEEDED" <<<"$out" \
  && ok "unwired hook surfaces as a WIRING NEEDED block, not a silent write" \
  || bad "no WIRING NEEDED block for the unwired hook"
[ ! -f .claude/settings.json ] \
  && ok "converge alone never touches .claude/settings.json" \
  || bad "converge wrote .claude/settings.json without consent"

# --- The corpus view's build: placed at the pin, never repository content ----
# The build a project holds must understand the corpus of the version the
# project is pinned to, so the same pass that stamps the estate places the
# build and stamps it with that same version and a digest over every byte
# placed. And the build is generated bytes, so it must land under the
# estate's own ignore and never become content of the repository. Both
# halves are asserted against the bootstrap run above, BEFORE any
# `git add`: after a commit an unignored build would already be tracked
# and a clean `git status` would prove nothing either way.
# @decision: built-bundle-fetched-at-pin
section built-bundle-fetched-at-pin
[ -f .ok-planner/browser/index.html ] \
  && ok "converge places the corpus view's build at the project's pin (.ok-planner/browser/)" \
  || bad "the corpus view's build was not placed at .ok-planner/browser/"
build_stamp_version=$(sed -n 's/.*Materialized by ok-planner v\([0-9][0-9A-Za-z.-]*[0-9A-Za-z]\).*/\1/p' \
  .ok-planner/browser/.build-stamp 2>/dev/null | head -1)
[ "$build_stamp_version" = "$suite_version" ] \
  && ok "the build stamp names the same suite version this pass stamped the estate with (v$suite_version)" \
  || bad "build stamp version '${build_stamp_version:-none}' disagrees with the estate stamp '$suite_version'"
grep -q '^build-sha256: [0-9a-f]\{64\}$' .ok-planner/browser/.build-stamp 2>/dev/null \
  && ok "the build stamp digests every byte placed, so a later diagnose can verify them" \
  || bad "the build stamp carries no digest over the placed bytes"
git check-ignore -q .ok-planner/browser/index.html \
  && ok "git itself ignores the placed build (the estate's own .gitignore)" \
  || bad "git does not ignore .ok-planner/browser/ — a generated build would become repository content"
if git status --porcelain --untracked-files=all | grep -q '^?? \.ok-planner/browser/'; then
  bad "the placed build is offered as repository content before any git add"
else
  ok "the placed build never appears in git status — excluded from repository content"
fi

# --- Consented wiring: the wire-hooks path is the only settings writer ------
bash "$planner_core" wire-hooks >/dev/null 2>&1
matcher=$(python3 -c "import json;print(json.load(open('.claude/settings.json'))['hooks']['SessionStart'][0]['matcher'])" 2>/dev/null)
[ "$matcher" = "startup|clear|compact" ] \
  && ok "wire-hooks transcribes the exact consented entry (startup|clear|compact)" \
  || bad "wire-hooks entry wrong or missing (matcher: ${matcher:-none})"

# --- Pass 2: repair after deliberate drift in a suite-owned file ------------
echo "local edit" >> .ok-planner/CLAUDE.md
if bash "$planner_core" diagnose >/dev/null 2>&1; then
  bad "diagnose missed drift in a suite-owned file"
else
  ok "diagnose reports drift in a suite-owned file (read-only, non-zero exit)"
fi
bash "$planner_core" >/dev/null 2>&1
grep -q "local edit" .ok-planner/CLAUDE.md \
  && bad "converge failed to repair the drifted suite-owned file" \
  || ok "converge repairs the drifted suite-owned file by overwrite"

# --- Pass 3: no-op on a compliant estate -------------------------------------
git add -A
git -c user.email=test@example.com -c user.name=test commit -qm "converged estate"
bash "$planner_core" >/dev/null 2>&1
if [ -z "$(git status --porcelain)" ]; then
  ok "third pass is a no-op: git status empty on a compliant estate"
else
  bad "third pass churned the working tree:"; git status --porcelain
fi
bash "$planner_core" diagnose >/dev/null 2>&1 \
  && ok "diagnose clean on the converged estate" \
  || bad "diagnose still reports findings on the converged estate"

# --- The build's four distinct diagnose findings, driven and repaired -------
# The stamp exists so a later diagnose can tell an intact build of this
# version from four failure modes it must not confuse: an absent build, a
# placement carrying no stamp (so which version's build it is cannot be
# told), a build belonging to another suite version, and a build corrupted
# in place under an intact stamp. Each is driven by mutating the converged
# estate and running the read-only mode, and each must be repairable by an
# ordinary converge — a diagnose that reports it but cannot be cleared is
# as useless as one that misses it.
# @decision: built-bundle-fetched-at-pin
section built-bundle-fetched-at-pin
build_finding() {  # build_finding <expected DRIFT text> <label>
  local out rc
  out=$(bash "$planner_core" diagnose 2>&1)
  rc=$?
  if [ "$rc" -ne 0 ] && grep -qF "DRIFT: $1" <<<"$out"; then
    ok "diagnose reports the $2 build (non-zero exit, nothing written)"
  else
    bad "diagnose did not report the $2 build (exit $rc)"
    grep -i browser <<<"$out"
  fi
  bash "$planner_core" >/dev/null 2>&1
  bash "$planner_core" diagnose >/dev/null 2>&1 \
    && ok "converge repairs the $2 build" \
    || bad "converge did not repair the $2 build"
}

rm -rf .ok-planner/browser
build_finding "missing: .ok-planner/browser/ (the corpus view's build for v${suite_version})" missing

rm -f .ok-planner/browser/.build-stamp
build_finding "unstamped: .ok-planner/browser/ carries no build stamp" unstamped

# An intact build of an earlier suite version: the stamp is well-formed,
# it simply is not this version's.
python3 - "$suite_version" <<'PY'
import sys
p = ".ok-planner/browser/.build-stamp"
s = open(p).read().replace("ok-planner v" + sys.argv[1], "ok-planner v0.0.0-earlier")
open(p, "w").write(s)
PY
build_finding "stale: .ok-planner/browser/ is not the carried v${suite_version} build" stale

# A placed byte altered under a stamp that still matches the carried
# build: only recomputing the digest over the placement catches this.
printf 'corrupted-in-place' >> .ok-planner/browser/index.html
build_finding "drifted: .ok-planner/browser/ no longer matches the build stamp it was placed with" drifted

# --- converge-project-estate: the upgrade sweep over a legacy estate --------
# An estate materialized by an earlier suite version carries payloads this
# version no longer owns and stories carrying the retired `## Falsifier`,
# `## Proof` and `## Acceptance` sections. All of it is suite-owned, so
# removing it is converge's job and not a consent question — but a sweep
# that overreaches is worse than one that under-reaches, so what survives
# matters as much as what goes: everything outside the retired sections
# must come through byte-for-byte. Pre-migration layout is the third
# thing: converge never migrates it, it reports every marker it found and
# points at the administration document.
# @story: converge-project-estate
section converge-project-estate
legacy=$(mktemp -d)
(
  cd "$legacy"
  git init -q .
  git -c user.email=test@example.com -c user.name=test commit -q --allow-empty -m init
)
mkdir -p "$legacy/.ok-planner/context" "$legacy/.ok-planner/hooks" "$legacy/.ok-planner/bin" \
         "$legacy/.ok-planner/design/stories" "$legacy/.ok-planner/design/concepts" \
         "$legacy/.ok-planner/design/decisions" "$legacy/.ok-planner/design/tensions" \
         "$legacy/.ok-planner/plans" "$legacy/.ok-planner/coverage" \
         "$legacy/.ok-planner/specs" "$legacy/.ok-planner/history/specs" \
         "$legacy/.ok-planner/backlogs" "$legacy/.ok-planner/history/backlogs"

# Retired estate payloads, one per path the sweep is responsible for.
echo "stale index" > "$legacy/.ok-planner/context/skills-index.md"
echo "stale hook"  > "$legacy/.ok-planner/hooks/user-prompt-submit"
echo "stale timer" > "$legacy/.ok-planner/bin/proof-timings"
echo '{"runs":[]}' > "$legacy/.ok-planner/proof-timings.json"

# Pre-migration markers converge reports but never migrates.
echo '{"id":1}' > "$legacy/.ok-planner/issues.jsonl"
echo "old notes" > "$legacy/.ok-planner/design/review-notes.md"
printf '# D\n\n## Choice\n\nc\n\n## Proof\n\np\n' > "$legacy/.ok-planner/design/decisions/d.md"

# The retired falsifier concept and its catalog line; the sibling concept
# line beside it proves the TOC edit is surgical.
echo "the retired kind" > "$legacy/.ok-planner/design/concepts/falsifier.md"
cat > "$legacy/.ok-planner/design/concepts.md" <<'MD'
# Concept catalog

- [`estate`](concepts/estate.md) — the project-side directory
- [`falsifier`](concepts/falsifier.md) — the retired kind
MD

# A story carrying all three retired sections interleaved with prose that
# must survive; the expectation beside it is the same file minus exactly
# those sections.
cat > "$legacy/.ok-planner/design/stories/keep.md" <<'MD'
# Story: keep

## Story

As a maintainer I want retired sections eliminated on sight so that a story
is its statement alone.

## Falsifier

A converged estate still carries a falsifier section.

## Proof

Run the administration harness.

## Notes

This prose sits outside the retired sections and must survive byte-for-byte.

## Acceptance

- every retired section is gone
MD
cat > "$legacy/expected-story.md" <<'MD'
# Story: keep

## Story

As a maintainer I want retired sections eliminated on sight so that a story
is its statement alone.

## Notes

This prose sits outside the retired sections and must survive byte-for-byte.

MD

legacy_out=$(cd "$legacy" && bash "$planner_core" 2>&1)

for p in context/skills-index.md hooks/user-prompt-submit bin/proof-timings proof-timings.json; do
  [ ! -e "$legacy/.ok-planner/$p" ] \
    && ok "retired estate payload swept on converge: .ok-planner/$p" \
    || bad "retired estate payload survived converge: .ok-planner/$p"
done
grep -qF "Retired payloads removed: context/skills-index.md hooks/user-prompt-submit bin/proof-timings proof-timings.json" \
  <<<"$legacy_out" \
  && ok "converge names every retired payload it removed" \
  || bad "converge did not report the retired payloads it removed"

if cmp -s "$legacy/expected-story.md" "$legacy/.ok-planner/design/stories/keep.md"; then
  ok "## Falsifier / ## Proof / ## Acceptance stripped, the rest of the story byte-for-byte intact"
else
  bad "the story sweep changed more (or less) than the three retired sections:"
  diff "$legacy/expected-story.md" "$legacy/.ok-planner/design/stories/keep.md"
fi
grep -qF "Retired story sections eliminated: 1 story file(s) stripped" <<<"$legacy_out" \
  && ok "converge reports the story files it stripped" \
  || bad "converge did not report the stripped story"
[ ! -e "$legacy/.ok-planner/design/concepts/falsifier.md" ] \
  && ok "the retired falsifier concept file is removed with the sections" \
  || bad "the retired falsifier concept file survived converge"
if grep -q 'falsifier' "$legacy/.ok-planner/design/concepts.md"; then
  bad "the falsifier line survived in the concept catalog"
elif grep -q 'estate' "$legacy/.ok-planner/design/concepts.md"; then
  ok "the catalog's falsifier line is removed and its sibling entries left alone"
else
  bad "the catalog edit took the sibling concept lines with it"
fi

# Every marker detect_premigration knows, seeded at once: the report is
# the whole set, in the order the detector walks them, on the last line.
expected_pre="plans coverage design/tensions specs history/specs backlogs history/backlogs decision-proof-sections design/review-notes.md issues.jsonl"
legacy_last=$(tail -1 <<<"$legacy_out")
[ "$legacy_last" = "PRE-MIGRATION LAYOUT PRESENT: ${expected_pre} - run the migration procedures in admin/ADMINISTRATION.md." ] \
  && ok "converge reports every pre-migration marker on its last line and points at ADMINISTRATION.md" \
  || bad "pre-migration report wrong on converge's last line: ${legacy_last}"
legacy_diag=$(cd "$legacy" && bash "$planner_core" diagnose 2>&1)
grep -qF "PRE-MIGRATION LAYOUT PRESENT: ${expected_pre}" <<<"$legacy_diag" \
  && ok "the read-only diagnose reports the same pre-migration set (converge migrates none of it)" \
  || bad "diagnose does not report the pre-migration set converge reported"
[ -d "$legacy/.ok-planner/specs" ] && [ -f "$legacy/.ok-planner/issues.jsonl" ] \
  && ok "pre-migration layout is reported, never migrated behind the owner's back" \
  || bad "converge migrated pre-migration layout instead of reporting it"

rm -rf "$legacy"

# --- one-command-suite-upkeep: the consolidated act over two families -------
section one-command-suite-upkeep
# The front door is a skill, so the dialogue itself is prompt-realized:
# the single consent question and the printed table are asserted against
# plugins/ok/skills/ok/SKILL.md, and everything the run is supposed to
# produce on disk is exercised here against a project carrying one
# integrated family and one carried-but-unintegrated family.
families_dir="$suite_repo/plugins/ok/families"
two=$(mktemp -d)
(
  cd "$two"
  git init -q .
  git -c user.email=test@example.com -c user.name=test commit -q --allow-empty -m init
)

# One family integrated: its marker is materialized by its own core.
(cd "$two" && bash "$planner_core" >/dev/null 2>&1)

integrated=""
candidates=""
for f in ok-planner ok-plumbline ok-workspaces; do
  if [ -d "$two/.$f" ]; then integrated="$integrated $f"; else candidates="$candidates $f"; fi
done
[ "$(echo $integrated)" = "ok-planner" ] \
  && ok "discovery by marker alone finds exactly the integrated family (ok-planner)" \
  || bad "discovery found '$(echo $integrated)' instead of ok-planner"
[ "$(echo $candidates)" = "ok-plumbline ok-workspaces" ] \
  && ok "the carried-but-unintegrated families are the bootstrap candidates" \
  || bad "bootstrap candidates wrong: '$(echo $candidates)'"

# The owner consents to one candidate; its profile is transcription of
# their answers, and administering it is the same one-pass shape.
mkdir -p "$two/.ok-workspaces"
cat > "$two/.ok-workspaces/config.json" <<'JSON'
{
  "stacks": [],
  "runtime": "none",
  "worktrees": { "dirPrefix": ".ok-workspaces/worktrees/", "branchPrefix": "wt/" },
  "srcTag": { "path": ".ok-workspaces/bin/src-tag" }
}
JSON
(cd "$two" && bash "$families_dir/ok-workspaces/admin/converge" >/dev/null 2>&1)
[ -f "$two/.claude/rules/ok-workspaces-cheatsheet.md" ] \
  && ok "the consented family is administered in the same pass (estate + cheatsheet materialized)" \
  || bad "the consented family was not administered"
[ ! -e "$two/.ok-plumbline" ] \
  && ok "the declined family is left alone — nothing bootstrapped without consent" \
  || bad "a declined family was bootstrapped anyway"

# The closing table: per family, carried version, project-stamped
# version, outcome — every cell readable off the filesystem the run
# leaves behind.
table_rows=0
for f in ok-planner ok-workspaces; do
  case "$f" in
    ok-planner)    stamp=$(sed -n 's/.*Materialized by ok-planner v\([0-9][0-9A-Za-z.-]*[0-9A-Za-z]\).*/\1/p' "$two/.ok-planner/CLAUDE.md" | head -1) ;;
    ok-workspaces) stamp=$(sed -n 's/.*Materialized by ok-workspaces v\([0-9][0-9A-Za-z.-]*[0-9A-Za-z]\).*/\1/p' "$two/.claude/rules/ok-workspaces-cheatsheet.md" | head -1) ;;
  esac
  if [ "$stamp" = "$suite_version" ]; then
    table_rows=$((table_rows + 1))
  else
    bad "closing table: $f stamped '${stamp:-none}', carried '$suite_version'"
  fi
done
[ "$table_rows" -eq 2 ] \
  && ok "the closing table has a row per administered family, carried and project-stamped versions agreeing (v$suite_version)" \
  || bad "the closing table cannot be built from the run's own output"

# The conduct is never vendored or offered.
if [ ! -e "$two/.ok-conduct" ] && [ ! -d "$two/.claude/skills/ok-conduct" ] \
   && [ -z "$(ls -1 "$two/.claude/rules" 2>/dev/null | grep -i conduct)" ]; then
  ok "the personal conduct is never vendored into the project"
else
  bad "the conduct leaked into the project"
fi

# --- vendored-skills: the contract's collision rule, read off the disk ------
# `audit` is a verb more than one family claims, so the contract says it
# materializes family-prefixed while every other verb keeps its name —
# which is only observable in a project that integrates two families, as
# this one now does. The expectation is built from the rule itself (family
# name, hyphen, verb) and never from a family's own vendoring map: a test
# that read the map would pass just as happily against a map that had
# dropped the prefix, which is the one failure it exists to catch. The
# rename has to reach inside the rendered file too — a skill that still
# tells the user to type `/audit` names a slash command that does not
# exist in the project.
# @decision: vendored-skills
section vendored-skills
for f in ok-planner ok-workspaces; do
  materialized=".claude/skills/${f}-audit"
  if [ -f "$two/$materialized/SKILL.md" ]; then
    ok "$f materializes the colliding audit verb family-prefixed ($materialized)"
  else
    bad "$f did not materialize the audit verb at $materialized"
    continue
  fi
  grep -q "^name: ${f}-audit$" "$two/$materialized/SKILL.md" \
    && ok "$f's vendored audit skill declares the materialized name in its frontmatter" \
    || bad "$f's vendored audit skill does not declare 'name: ${f}-audit'"
  grep -q "/${f}-audit" "$two/$materialized/SKILL.md" \
    && ok "$f's vendored audit skill reaches itself by the materialized slash command (/${f}-audit)" \
    || bad "$f's vendored audit skill carries no /${f}-audit reference"
  if grep -qE '/audit([^-]|$)' "$two/$materialized/SKILL.md"; then
    bad "$f's vendored audit skill still self-references the bare /audit slash command:"
    grep -nE '/audit([^-]|$)' "$two/$materialized/SKILL.md"
  else
    ok "$f's vendored audit skill has no bare /audit self-reference left"
  fi
done
[ ! -e "$two/.claude/skills/audit" ] \
  && ok "no bare .claude/skills/audit/ — the colliding verb never materializes unprefixed" \
  || bad "a bare .claude/skills/audit/ materialized despite the collision rule"

rm -rf "$two"

exit $fail
